esphome:
  platform: ESP8266
  board: esp12e
  name: test

# Enable Home Assistant API
api:
  password: abcd1234

# Make sure you can upload new firmware OTA

ota:
  password: "2b76b9fd0e83315a866c18dcea62677c"

wifi:
  ssid: "Kasteel"
  password: "@1KODPCKKn!HKqiArj"
  # manual_ip:
    #   static_ip: 10.222.15.33
    #   gateway: 10.222.14.138
    #   subnet: 255.255.254.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "Qb2BgmhQxev8"
  fast_connect: true

captive_portal:

# Enable logging
logger:
  esp8266_store_log_strings_in_flash: false
  # Make sure logging is not using the serial port
  baud_rate: 0

external_components:
  - source: github://dentra/esphome-components

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600
  parity: EVEN

switch:
  # All the options of zmai90v1 platform are optional
  - platform: zmai90v1
    name: Switch
    # main switch pin, GPIOPin, default: GPIO12
    switch_pin: GPIO12
    # button pin, GPIOPin, default: GPIO13
    button_pin: GPIO13
    # button, BinarySensor
    button:
      name: Button
      # automatically bind button to the main switch, boolean, default: true
      # works only with conjunction with button
      bind_to_switch: true
    # energy sensor in kWh, Sensor
    energy:
      name: Energy
    # voltage sensor in V, Sensor,
    voltage:
      name: Voltage
    # current sensor in A, Sensor,
    current:
      name: Current
    # active power in W, Sensor
    active_power:
      name: Active Power
    # active power in VAR, Sensor
    reactive_power:
      name: Reactive Power
    # active power in VA, Sensor
    apparent_power:
      name: Apparent Power
    # power factor, Sensor
    power_factor:
      name: Power Factor
    # frequency in Hz, Sensor
    frequency:
      name: Frequency
    update_interval: 30s
