substitutions:
  devicename: "x1-relay-02-"
  friendly_name: "x1-relay-02"
  device_description: "x1-relay-02"
  logger_level: DEBUG
  new_ota_passwd: "12345abcde"
  reboot_timeout: 60s
  static_ip: "127"

packages:
  device_base: !include devices/esp12f_relay_x1_v2_1.yaml

esphome:
  name_add_mac_suffix: true
#  <<: !include esphome/on_boot_ota_pw.yaml

wifi:
  # use_address: 10.222.15.122
  <<: !include devices/wifi/wifi_kasteel_fixed.yaml # manual-ip kasteel using $static_ip