substitutions:
  devicename: "yunshan-relay-03-"
  friendly_name: "yunshan-relay-03"
  device_description: "yunshan-relay-03"
  logger_level: DEBUG
  new_ota_passwd: "<new_ota_password>"
  reboot_timeout: 60s
  static_ip: "129"

packages:
  device_base: !include devices/yunshan_relay.yaml

esphome:
  name_add_mac_suffix: true
#  <<: !include esphome/on_boot_ota_pw.yaml

wifi:
  # use_address: 10.222.15.37
  <<: !include devices/wifi/wifi_kasteel_fixed.yaml # manual-ip outdoorwrt using $static_ip