substitutions:
  devicename: "yunshan-relay-02-"
  friendly_name: "garage_door"
  device_description: "overhead door garage"
  logger_level: DEBUG
  new_ota_passwd: "<new_ota_password>"
  reboot_timeout: 60s
  static_ip: "126"

packages:
  device_base: !include devices/yunshan_relay.yaml

esphome:
  name_add_mac_suffix: true
#  <<: !include esphome/on_boot_ota_pw.yaml

wifi:
  # use_address: 192.168.5.20
  <<: !include devices/wifi/wifi_kasteel_fixed.yaml # manual-ip outdoorwrt using $static_ip