---

<<: !include boards/esp12e.yaml

<<: !include wifi/wifi.yaml

<<: !include common/common.yaml # api, ota, web_server, text_sensors, logger, status_led

<<: !include common/binary_sensors.yaml # connection status

wifi:
  power_save_mode: light
  
captive_portal:

sensor:
  - !include sensors/wifi_signal.yaml
  - !include sensors/uptime.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
      inverted: True
    name: "${friendly_name} Optocoupler"

switch:
  - !include switches/restart.yaml
#  - !include switches/shutdown.yaml
  - platform: gpio
    name: "${friendly_name} Relay"
    icon: "mdi:remote"
    pin: GPIO4
    id: relay1
    on_turn_on:
      - delay: 400ms
      - switch.turn_off: relay1