substitutions:
  devicename: yunshan_relay

<<: !include boards/esp12e.yaml

<<: !include wifi/wifi.yaml
  power_save_mode: light # none, light, high
captive_portal:

<<: !include common/common.yaml # api, ota, web_server, text_sensors, logger, status_led

<<: !include sensors.yaml # wifi_signal, uptime

<<: !include binary_sensors.yaml # connection status
  - platform: gpio
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
      inverted: True
    name: "${friendly_name} Optocoupler"

<<: !include switches.yaml
  - <<: !include switches/shutdown.yaml
  - platform: gpio
      name: "${friendly_name} Relay"
      icon: "mdi:remote"
      pin: GPIO4
      id: relay1
      on_turn_on:
        - delay: 400ms
        - switch.turn_off: relay1